export interface CountryData {
  code: string
  name: string
  dialCode: string
  flag: string
  format: string
  placeholder: string
}

// Popular countries first, rest alphabetically
const POPULAR_CODES = [
  'US', 'CA', 'GB', 'AU', 'DE', 'FR', 'NL', 'JP', 'IN', 'BR', 'MX',
  'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'FI', 'IE', 'NZ', 'SG', 'HK',
  'KR', 'CN', 'AE', 'SA', 'ZA', 'IL', 'PT', 'AT', 'BE',
]

const ALL_COUNTRIES: CountryData[] = [
  // === POPULAR ===
  { code: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸', format: 'XXX-XXX-XXXX', placeholder: '555-123-4567' },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', format: 'XXX-XXX-XXXX', placeholder: '416-555-1234' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧', format: 'XXXX XXXXXX', placeholder: '7911 123456' },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺', format: 'XXXX XXX XXX', placeholder: '0412 345 678' },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪', format: 'XXX XXXXXXXX', placeholder: '151 12345678' },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', format: 'X XX XX XX XX', placeholder: '6 12 34 56 78' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱', format: 'X XXXXXXXX', placeholder: '6 12345678' },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵', format: 'XXX-XXXX-XXXX', placeholder: '90-1234-5678' },
  { code: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳', format: 'XXXXX XXXXX', placeholder: '98765 43210' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷', format: 'XX XXXXX-XXXX', placeholder: '11 91234-5678' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽', format: 'XX XXXX XXXX', placeholder: '55 1234 5678' },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹', format: 'XXX XXX XXXX', placeholder: '312 345 6789' },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸', format: 'XXX XXX XXX', placeholder: '612 345 678' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭', format: 'XX XXX XX XX', placeholder: '78 123 45 67' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪', format: 'XXX-XXX XX XX', placeholder: '70-123 45 67' },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴', format: 'XXX XX XXX', placeholder: '412 34 567' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰', format: 'XX XX XX XX', placeholder: '12 34 56 78' },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮', format: 'XX XXX XXXX', placeholder: '50 123 4567' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪', format: 'XX XXX XXXX', placeholder: '85 123 4567' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', format: 'XX XXX XXXX', placeholder: '21 123 4567' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', format: 'XXXX XXXX', placeholder: '8123 4567' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', format: 'XXXX XXXX', placeholder: '9123 4567' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷', format: 'XX-XXXX-XXXX', placeholder: '10-1234-5678' },
  { code: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳', format: 'XXX XXXX XXXX', placeholder: '131 2345 6789' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪', format: 'XX XXX XXXX', placeholder: '50 123 4567' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', format: 'XX XXX XXXX', placeholder: '50 123 4567' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦', format: 'XX XXX XXXX', placeholder: '82 123 4567' },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱', format: 'XX-XXX-XXXX', placeholder: '50-123-4567' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', format: 'XXX XXX XXX', placeholder: '912 345 678' },
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹', format: 'XXX XXXXXXX', placeholder: '664 1234567' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪', format: 'XXX XX XX XX', placeholder: '471 23 45 67' },

  // === ALL COUNTRIES (alphabetical by name, excluding popular above) ===
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', format: 'XX XXX XXXX', placeholder: '70 123 4567' },
  { code: 'AL', name: 'Albania', dialCode: '+355', flag: '🇦🇱', format: 'XX XXX XXXX', placeholder: '67 123 4567' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿', format: 'XXX XX XX XX', placeholder: '555 12 34 56' },
  { code: 'AS', name: 'American Samoa', dialCode: '+1', flag: '🇦🇸', format: 'XXX-XXX-XXXX', placeholder: '684-123-4567' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', flag: '🇦🇩', format: 'XXX XXX', placeholder: '312 345' },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', format: 'XXX XXX XXX', placeholder: '923 123 456' },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1', flag: '🇦🇬', format: 'XXX-XXX-XXXX', placeholder: '268-123-4567' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷', format: 'XX XXXX-XXXX', placeholder: '11 1234-5678' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', flag: '🇦🇲', format: 'XX XXXXXX', placeholder: '91 123456' },
  { code: 'AW', name: 'Aruba', dialCode: '+297', flag: '🇦🇼', format: 'XXX XXXX', placeholder: '560 1234' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿', format: 'XX XXX XX XX', placeholder: '50 123 45 67' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1', flag: '🇧🇸', format: 'XXX-XXX-XXXX', placeholder: '242-123-4567' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', format: 'XXXX XXXX', placeholder: '3123 4567' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', format: 'XXXX-XXXXXX', placeholder: '1712-345678' },
  { code: 'BB', name: 'Barbados', dialCode: '+1', flag: '🇧🇧', format: 'XXX-XXX-XXXX', placeholder: '246-123-4567' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', flag: '🇧🇾', format: 'XX XXX-XX-XX', placeholder: '29 123-45-67' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿', format: 'XXX-XXXX', placeholder: '612-3456' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯', format: 'XX XXX XXX', placeholder: '90 123 456' },
  { code: 'BM', name: 'Bermuda', dialCode: '+1', flag: '🇧🇲', format: 'XXX-XXX-XXXX', placeholder: '441-123-4567' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹', format: 'XX XXX XXX', placeholder: '17 123 456' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: '🇧🇴', format: 'XXX XXXXX', placeholder: '712 34567' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦', format: 'XX XXX XXX', placeholder: '63 123 456' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼', format: 'XX XXX XXX', placeholder: '71 123 456' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', format: 'XXX XXXX', placeholder: '712 3456' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬', format: 'XXX XXX XXX', placeholder: '888 123 456' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', format: 'XX XX XX XX', placeholder: '70 12 34 56' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮', format: 'XX XX XXXX', placeholder: '79 12 3456' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: '🇰🇭', format: 'XXX XXX XXX', placeholder: '912 345 678' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: '🇨🇲', format: 'XXX XXX XXX', placeholder: '612 345 678' },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻', format: 'XXX XXXX', placeholder: '991 2345' },
  { code: 'KY', name: 'Cayman Islands', dialCode: '+1', flag: '🇰🇾', format: 'XXX-XXX-XXXX', placeholder: '345-123-4567' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫', format: 'XX XX XX XX', placeholder: '70 12 34 56' },
  { code: 'TD', name: 'Chad', dialCode: '+235', flag: '🇹🇩', format: 'XX XX XX XX', placeholder: '66 12 34 56' },
  { code: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱', format: 'X XXXX XXXX', placeholder: '9 1234 5678' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴', format: 'XXX XXX XXXX', placeholder: '312 123 4567' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', flag: '🇰🇲', format: 'XXX XXXX', placeholder: '312 3456' },
  { code: 'CG', name: 'Congo', dialCode: '+242', flag: '🇨🇬', format: 'XX XXX XXXX', placeholder: '06 123 4567' },
  { code: 'CD', name: 'Congo (DRC)', dialCode: '+243', flag: '🇨🇩', format: 'XX XXX XXXX', placeholder: '81 123 4567' },
  { code: 'CK', name: 'Cook Islands', dialCode: '+682', flag: '🇨🇰', format: 'XX XXX', placeholder: '71 234' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', format: 'XXXX XXXX', placeholder: '8123 4567' },
  { code: 'CI', name: 'Côte d\'Ivoire', dialCode: '+225', flag: '🇨🇮', format: 'XX XX XX XX', placeholder: '01 12 34 56' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', flag: '🇭🇷', format: 'XX XXX XXXX', placeholder: '91 234 5678' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺', format: 'X XXX XXXX', placeholder: '5 123 4567' },
  { code: 'CW', name: 'Curaçao', dialCode: '+599', flag: '🇨🇼', format: 'XXX XXXX', placeholder: '912 3456' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: '🇨🇾', format: 'XX XXX XXX', placeholder: '96 123 456' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿', format: 'XXX XXX XXX', placeholder: '601 123 456' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1', flag: '🇩🇴', format: 'XXX-XXX-XXXX', placeholder: '809-123-4567' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: '🇪🇨', format: 'XX XXX XXXX', placeholder: '98 123 4567' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', format: 'XX XXXX XXXX', placeholder: '10 1234 5678' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: '🇸🇻', format: 'XXXX XXXX', placeholder: '7123 4567' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶', format: 'XXX XXX XXX', placeholder: '222 123 456' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', flag: '🇪🇷', format: 'X XXX XXX', placeholder: '7 123 456' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', flag: '🇪🇪', format: 'XXXX XXXX', placeholder: '5123 4567' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: '🇸🇿', format: 'XXXX XXXX', placeholder: '7612 3456' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', format: 'XX XXX XXXX', placeholder: '91 123 4567' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: '🇫🇯', format: 'XXX XXXX', placeholder: '912 3456' },
  { code: 'FK', name: 'Falkland Islands', dialCode: '+500', flag: '🇫🇰', format: 'XXXXX', placeholder: '51234' },
  { code: 'FO', name: 'Faroe Islands', dialCode: '+298', flag: '🇫🇴', format: 'XXXXXX', placeholder: '123456' },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', flag: '🇫🇲', format: 'XXX XXXX', placeholder: '912 3456' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', format: 'X XX XX XX', placeholder: '6 12 34 56' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', flag: '🇬🇪', format: 'XXX XXX XXX', placeholder: '599 123 456' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', format: 'XX XXX XXXX', placeholder: '20 123 4567' },
  { code: 'GI', name: 'Gibraltar', dialCode: '+350', flag: '🇬🇮', format: 'XXXX XXXX', placeholder: '5412 3456' },
  { code: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷', format: 'XXX XXX XXXX', placeholder: '691 234 5678' },
  { code: 'GL', name: 'Greenland', dialCode: '+299', flag: '🇬🇱', format: 'XXXXXX', placeholder: '123456' },
  { code: 'GD', name: 'Grenada', dialCode: '+1', flag: '🇬🇩', format: 'XXX-XXX-XXXX', placeholder: '473-123-4567' },
  { code: 'GP', name: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵', format: 'XXX XX XX XX', placeholder: '690 12 34 56' },
  { code: 'GU', name: 'Guam', dialCode: '+1', flag: '🇬🇺', format: 'XXX-XXX-XXXX', placeholder: '671-123-4567' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', format: 'X XXX XXXX', placeholder: '5 123 4567' },
  { code: 'GG', name: 'Guernsey', dialCode: '+44', flag: '🇬🇬', format: 'XXXX XXXXXX', placeholder: '7911 123456' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', flag: '🇬🇳', format: 'XXX XX XX XX', placeholder: '622 12 34 56' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼', format: 'XXX XXXX', placeholder: '955 1234' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾', format: 'XXX XXXX', placeholder: '612 3456' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', flag: '🇭🇹', format: 'XXXX-XXXX', placeholder: '3412-5678' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳', format: 'XXXX-XXXX', placeholder: '9123-4567' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', flag: '🇭🇺', format: 'XX XXX XXXX', placeholder: '30 123 4567' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', flag: '🇮🇸', format: 'XXX XXXX', placeholder: '612 3456' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', format: 'XXX-XXXX-XXXX', placeholder: '812-3456-7890' },
  { code: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', format: 'XXX XXX XXXX', placeholder: '912 123 4567' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶', format: 'XXX XXX XXXX', placeholder: '770 123 4567' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1', flag: '🇯🇲', format: 'XXX-XXX-XXXX', placeholder: '876-123-4567' },
  { code: 'JE', name: 'Jersey', dialCode: '+44', flag: '🇯🇪', format: 'XXXX XXXXXX', placeholder: '7911 123456' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴', format: 'X XXXX XXXX', placeholder: '7 1234 5678' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿', format: 'XXX XXX XXXX', placeholder: '701 123 4567' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', format: 'XXX XXXXXX', placeholder: '712 345678' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: '🇰🇮', format: 'XXXX XXXX', placeholder: '5123 4567' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', format: 'XXXX XXXX', placeholder: '9123 4567' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flag: '🇰🇬', format: 'XXX XXX XXX', placeholder: '700 123 456' },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦', format: 'XX XXX XXXXX', placeholder: '20 22 123456' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', flag: '🇱🇻', format: 'XX XXX XXX', placeholder: '20 123 456' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧', format: 'XX XXX XXX', placeholder: '71 123 456' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', format: 'XXXX XXXX', placeholder: '5012 3456' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', flag: '🇱🇷', format: 'XX XXX XXXX', placeholder: '88 123 4567' },
  { code: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾', format: 'XX-XXXXXXX', placeholder: '91-1234567' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', format: 'XXX XXXX', placeholder: '660 1234' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', flag: '🇱🇹', format: 'XXX XXXXX', placeholder: '612 34567' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', format: 'XXX XXX XXX', placeholder: '621 123 456' },
  { code: 'MO', name: 'Macao', dialCode: '+853', flag: '🇲🇴', format: 'XXXX XXXX', placeholder: '6812 3456' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', format: 'XX XXX XXXX', placeholder: '34 12 34567' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼', format: 'XX XXX XXXX', placeholder: '99 123 4567' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', format: 'XX-XXX XXXX', placeholder: '12-345 6789' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', format: 'XXX-XXXX', placeholder: '771-2345' },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', format: 'XX XX XX XX', placeholder: '70 12 34 56' },
  { code: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹', format: 'XXXX XXXX', placeholder: '9912 3456' },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭', format: 'XXX-XXXX', placeholder: '235-1234' },
  { code: 'MQ', name: 'Martinique', dialCode: '+596', flag: '🇲🇶', format: 'XXX XX XX XX', placeholder: '696 12 34 56' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', flag: '🇲🇷', format: 'XXXX XXXX', placeholder: '2212 3456' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: '🇲🇺', format: 'XXXX XXXX', placeholder: '5123 4567' },
  { code: 'YT', name: 'Mayotte', dialCode: '+262', flag: '🇾🇹', format: 'XXX XX XX XX', placeholder: '639 12 34 56' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', flag: '🇲🇩', format: 'XX XXX XXX', placeholder: '62 123 456' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨', format: 'XX XX XX XX', placeholder: '612 34 56 78' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: '🇲🇳', format: 'XXXX XXXX', placeholder: '8812 3456' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', flag: '🇲🇪', format: 'XX XXX XXX', placeholder: '67 123 456' },
  { code: 'MS', name: 'Montserrat', dialCode: '+1', flag: '🇲🇸', format: 'XXX-XXX-XXXX', placeholder: '664-123-4567' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦', format: 'XXXX-XXXXXX', placeholder: '6123-456789' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', format: 'XX XXX XXXX', placeholder: '84 123 4567' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', format: 'XX XXX XXXX', placeholder: '91 234 5678' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', flag: '🇳🇦', format: 'XX XXX XXXX', placeholder: '81 123 4567' },
  { code: 'NR', name: 'Nauru', dialCode: '+674', flag: '🇳🇷', format: 'XXXX XXXX', placeholder: '5512 3456' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵', format: 'XX-XXXXXXX', placeholder: '98-12345678' },
  { code: 'NC', name: 'New Caledonia', dialCode: '+687', flag: '🇳🇨', format: 'XX XX XX', placeholder: '75 12 34' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', format: 'XXXX XXXX', placeholder: '8123 4567' },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', format: 'XX XX XX XX', placeholder: '90 12 34 56' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', format: 'XXX XXX XXXX', placeholder: '802 123 4567' },
  { code: 'NU', name: 'Niue', dialCode: '+683', flag: '🇳🇺', format: 'XXXX XXX', placeholder: '1234 56' },
  { code: 'NF', name: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫', format: 'XX XXX', placeholder: '3 123' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', flag: '🇲🇰', format: 'XX XXX XXX', placeholder: '70 123 456' },
  { code: 'MP', name: 'Northern Mariana Islands', dialCode: '+1', flag: '🇲🇵', format: 'XXX-XXX-XXXX', placeholder: '670-123-4567' },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', format: 'XXXX XXXX', placeholder: '9123 4567' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', format: 'XXX XXXXXXX', placeholder: '300 1234567' },
  { code: 'PW', name: 'Palau', dialCode: '+680', flag: '🇵🇼', format: 'XXX XXXX', placeholder: '775 1234' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸', format: 'XX XXX XXXX', placeholder: '59 123 4567' },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', format: 'XXXX-XXXX', placeholder: '6123-4567' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬', format: 'XXX XXXX', placeholder: '712 3456' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', format: 'XXX XXX XXXX', placeholder: '981 123 4567' },
  { code: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪', format: 'XXX XXX XXX', placeholder: '912 345 678' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', format: 'XXX XXX XXXX', placeholder: '912 345 6789' },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱', format: 'XXX XXX XXX', placeholder: '512 123 456' },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1', flag: '🇵🇷', format: 'XXX-XXX-XXXX', placeholder: '787-123-4567' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', format: 'XXXX XXXX', placeholder: '3312 3456' },
  { code: 'RE', name: 'Réunion', dialCode: '+262', flag: '🇷🇪', format: 'XXX XX XX XX', placeholder: '692 12 34 56' },
  { code: 'RO', name: 'Romania', dialCode: '+40', flag: '🇷🇴', format: 'XXX XXX XXX', placeholder: '712 345 678' },
  { code: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺', format: 'XXX XXX-XX-XX', placeholder: '912 345-67-89' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', format: 'XXX XXX XXX', placeholder: '780 123 456' },
  { code: 'BL', name: 'Saint Barthélemy', dialCode: '+590', flag: '🇧🇱', format: 'XXX XX XX XX', placeholder: '690 12 34 56' },
  { code: 'SH', name: 'Saint Helena', dialCode: '+290', flag: '🇸🇭', format: 'XXXX', placeholder: '5123' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1', flag: '🇰🇳', format: 'XXX-XXX-XXXX', placeholder: '869-123-4567' },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1', flag: '🇱🇨', format: 'XXX-XXX-XXXX', placeholder: '758-123-4567' },
  { code: 'MF', name: 'Saint Martin', dialCode: '+590', flag: '🇲🇫', format: 'XXX XX XX XX', placeholder: '690 12 34 56' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', flag: '🇵🇲', format: 'XXX XX XX', placeholder: '412 34 56' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1', flag: '🇻🇨', format: 'XXX-XXX-XXXX', placeholder: '784-123-4567' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸', format: 'XX XXXX', placeholder: '72 1234' },
  { code: 'SM', name: 'San Marino', dialCode: '+378', flag: '🇸🇲', format: 'XXX XXX XXXX', placeholder: '6612 345 678' },
  { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', flag: '🇸🇹', format: 'XXX XXXX', placeholder: '981 2345' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳', format: 'XX XXX XXXX', placeholder: '77 123 4567' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', flag: '🇷🇸', format: 'XX XXX XXXX', placeholder: '60 123 4567' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', format: 'X XXX XXX', placeholder: '2 123 456' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', format: 'XX XXX XXX', placeholder: '76 123 456' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: '🇸🇰', format: 'XXX XXX XXX', placeholder: '912 345 678' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', flag: '🇸🇮', format: 'XX XXX XXX', placeholder: '31 123 456' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧', format: 'XX XXX', placeholder: '74 123' },
  { code: 'SO', name: 'Somalia', dialCode: '+252', flag: '🇸🇴', format: 'XX XXX XXX', placeholder: '61 234 567' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', format: 'XX XXX XXXX', placeholder: '71 123 4567' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩', format: 'XX XXX XXXX', placeholder: '91 123 4567' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷', format: 'XXX-XXXX', placeholder: '712-3456' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', dialCode: '+47', flag: '🇸🇯', format: 'XXX XX XXX', placeholder: '412 34 567' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱', format: 'XXX XXXX', placeholder: '772 1234' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳', format: 'XX XXX XXX', placeholder: '20 123 456' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷', format: 'XXX XXX XX XX', placeholder: '532 123 45 67' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: '🇹🇲', format: 'XX XXXXXX', placeholder: '61 123456' },
  { code: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1', flag: '🇹🇨', format: 'XXX-XXX-XXXX', placeholder: '649-123-4567' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻', format: 'XXXXX', placeholder: '90123' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬', format: 'XXX XXXXXXX', placeholder: '712 345678' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', format: 'XX XXX XX XX', placeholder: '50 123 45 67' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', format: 'X XXX XXXX', placeholder: '9 123 4567' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿', format: 'XX XXX XX XX', placeholder: '90 123 45 67' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺', format: 'XXXXX XXX', placeholder: '55123 45' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', format: 'XXX-XXXXXXX', placeholder: '412-1234567' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', format: 'XX XXX XX XX', placeholder: '91 123 45 67' },
  { code: 'VG', name: 'British Virgin Islands', dialCode: '+1', flag: '🇻🇬', format: 'XXX-XXX-XXXX', placeholder: '284-123-4567' },
  { code: 'VI', name: 'U.S. Virgin Islands', dialCode: '+1', flag: '🇻🇮', format: 'XXX-XXX-XXXX', placeholder: '340-123-4567' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪', format: 'XXX XXX XXX', placeholder: '712 345 678' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: '🇿🇲', format: 'XX XXX XXXX', placeholder: '95 123 4567' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', format: 'XX XXX XXXX', placeholder: '71 123 4567' },
]

const popularSet = new Set(POPULAR_CODES)

const popular = ALL_COUNTRIES.filter((c) => popularSet.has(c.code))
const rest = ALL_COUNTRIES.filter((c) => !popularSet.has(c.code)).sort((a, b) =>
  a.name.localeCompare(b.name),
)

export const COUNTRIES: CountryData[] = [...popular, ...rest]

const byCode = new Map<string, CountryData>()
for (const c of COUNTRIES) {
  if (!byCode.has(c.code)) byCode.set(c.code, c)
}

export function getCountryByCode(code: string): CountryData | undefined {
  return byCode.get(code.toUpperCase())
}
