/**
 * Database Types (Generated by Supabase)
 *
 * THIS FILE IS AUTO-GENERATED by: npm run gen:db
 * DO NOT EDIT MANUALLY - changes will be overwritten
 *
 * Last generated: Manual placeholder (will be replaced)
 *
 * IMPORTANT:
 * - Run `npm run gen:db` after any database schema changes
 * - CI will fail if this file is out of sync with DB
 * - These are the canonical DB types (snake_case, nullables)
 */

// TODO: This will be replaced by Supabase type generation in Phase 1b
// For now, manually define key types based on schema

export interface Database {
  public: {
    Tables: {
      properties: {
        Row: {
          id: string
          name: string
          slug: string
          owner_id: string | null
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          country: string | null
          property_type: string | null
          description: string | null
          amenities: unknown
          check_in_time: string | null
          check_out_time: string | null
          timezone: string | null
          status: string | null
          settings: unknown
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['properties']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['properties']['Insert']>
      }
      sites: {
        Row: {
          id: string
          property_id: string
          site_number: string
          site_name: string | null
          site_type: 'tent' | 'rv' | 'cabin' | 'glamping' | 'yurt' | 'other'
          max_occupancy: number
          max_vehicles: number
          size_sqft: number | null
          hookups: unknown // JSONB
          amenities: unknown // JSONB
          base_price: number // DECIMAL - will become BIGINT in Phase 2
          weekend_price: number | null
          status: 'available' | 'unavailable' | 'maintenance'
          description: string | null
          images: unknown // JSONB
          location_map: unknown | null
          allow_pets: boolean
          pet_fee: number | null
          ada_accessible: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['sites']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['sites']['Insert']>
      }
      guests: {
        Row: {
          id: string
          property_id: string
          user_id: string | null
          first_name: string
          last_name: string
          email: string
          phone: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          country: string | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['guests']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['guests']['Insert']>
      }
      reservations: {
        Row: {
          id: string
          property_id: string
          site_id: string
          guest_id: string
          confirmation_number: string
          check_in_date: string
          check_out_date: string
          num_adults: number
          num_children: number
          num_pets: number
          num_vehicles: number
          vehicle_info: unknown
          status: 'pending' | 'confirmed' | 'checked_in' | 'checked_out' | 'cancelled' | 'no_show'
          total_amount: number // DECIMAL - will become BIGINT in Phase 2
          paid_amount: number // DECIMAL - will become BIGINT in Phase 2
          payment_status: 'unpaid' | 'partial' | 'paid' | 'refunded'
          special_requests: string | null
          notes: string | null
          source: string
          created_at: string
          updated_at: string
          cancelled_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['reservations']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['reservations']['Insert']>
      }
      payments: {
        Row: {
          id: string
          property_id: string
          reservation_id: string
          amount: number // DECIMAL - will become BIGINT in Phase 2
          payment_method: 'credit_card' | 'debit_card' | 'cash' | 'check' | 'bank_transfer' | 'other'
          payment_status: 'pending' | 'completed' | 'failed' | 'refunded'
          stripe_payment_id: string | null
          transaction_id: string | null
          notes: string | null
          processed_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['payments']['Insert']>
      }
    }
  }
}

// ============================================================================
// Convenience Type Exports
// ============================================================================

export type Site = Database['public']['Tables']['sites']['Row']
export type SiteInsert = Database['public']['Tables']['sites']['Insert']
export type SiteUpdate = Database['public']['Tables']['sites']['Update']

export type Reservation = Database['public']['Tables']['reservations']['Row']
export type ReservationInsert = Database['public']['Tables']['reservations']['Insert']
export type ReservationUpdate = Database['public']['Tables']['reservations']['Update']

export type Guest = Database['public']['Tables']['guests']['Row']
export type GuestInsert = Database['public']['Tables']['guests']['Insert']
export type GuestUpdate = Database['public']['Tables']['guests']['Update']

export type Payment = Database['public']['Tables']['payments']['Row']
export type PaymentInsert = Database['public']['Tables']['payments']['Insert']
export type PaymentUpdate = Database['public']['Tables']['payments']['Update']

export type Property = Database['public']['Tables']['properties']['Row']
export type PropertyInsert = Database['public']['Tables']['properties']['Insert']
export type PropertyUpdate = Database['public']['Tables']['properties']['Update']
